In [3]:
import numpy as np
import cv2
from grid_detection import *
import keras
from keras.models import load_model

import matplotlib.pyplot as plt


Using TensorFlow backend.


In [4]:
#reagange list in list of list for each row:
def rearange_list(nlist):
    dlist=[]
    for i in range(0, 9):
        k=9*i
        l=k+9
        sub_list=nlist[k:l]
        dlist.append(sub_list)
    return np.matrix(dlist)


#check if a value is a possible fix for an empty slot
def verify_possile_value(x, y, n, grid):
    for i in range(0, 9):
        if grid[x, i]==n:
            return False
        
    for i in range(0, 9):
        if grid[i, y]==n:
            return False
    x0=(x//3)*3
    y0=(y//3)*3
    for i in range(0, 3):
        for j in range(0, 3):
            if grid[x0+i, y0+j]==n:
                return False
            
    return True



#fill in the empty slots:
def grid_solver(grid):
    for x in range(9):
        for y in range(9):
            if grid[x, y]==0:
                for n in range(1, 10):
                    if verify_possile_value(x, y, n, grid):
                        grid[x, y]=n
                        result=grid_solver(grid)
                        
                        if result is not None:
                            return result
                        
                        grid[x, y]=0 #Backtracking
                return None               
    return grid




        

In [5]:
digits, coord=detect_grid_image('sample_img/su4.jpg')

In [6]:
model_path='models/digit_recognition_model2.h5'
model = load_model(model_path)
pred=model.predict(digits)

In [7]:
list_values=list(pred.argmax(1))
matrix_cell=rearange_list(list_values)
print(matrix_cell)

[[0 0 0 0 2 1 0 3 4]
 [6 0 0 0 0 3 2 0 0]
 [0 0 0 5 0 0 0 6 0]
 [4 0 9 0 5 0 0 0 0]
 [0 2 0 0 0 0 0 4 0]
 [0 0 0 0 7 0 9 0 2]
 [0 9 0 0 0 6 0 0 0]
 [0 0 1 2 0 0 0 0 6]
 [3 7 0 4 8 0 0 0 0]]


In [ ]:
result=grid_solver(matrix_cell)
print(result)